### ISSUE TITLE
Node Steward Flow

### ISSUE THREAD

**Issue by hubsmoke** [desci-labs/nodes-web#53]
- [ ] Update "My Collection": Toggle Node Steward vs Original Author
- [ ] When you create a Node, you choose what your role is
- [ ] Data Model Change: Add Node Steward (current profile) public wallet address  to the metadata of the node under author (allow user to mark themselves as  a node steward)
- [ ] Adding a Node has different metadata requirements (metadata are suggestions and the requirements are different in terms of what makes a valid submission)
- [ ] If you are a Node steward, commit pane has different Tint (purple)
- [ ] Commit Flow: Allow user to make licensing suggestion (commit-step licensing modal from pre-commit requirement)
- [ ] Commit Flow: Ensure all components have licenses / warnings displayed for commit-step Licensing window
- [ ] Email template for invite
- [ ] Invite / accept flow
![Image](https://user-images.githubusercontent.com/278886/232242552-616fd18d-c557-44dd-b28d-8dcb04320b27.png)

![Image](https://user-images.githubusercontent.com/278886/233865304-b62cf4d9-4593-479a-b19c-e9b977a9a6c6.png)

![Image](https://user-images.githubusercontent.com/278886/233865340-78a70a76-4d96-4aa2-8b9c-12ae8c8363d3.png)

![Image](https://user-images.githubusercontent.com/278886/233865376-4056b756-2ad6-4a7b-b5c5-5124223cf58e.png)

![Image](https://user-images.githubusercontent.com/278886/232242825-4f0fdc90-c57c-4160-a4f3-14bdfce446f3.png)

![Image](https://user-images.githubusercontent.com/278886/232243651-802164ff-cc64-402e-9a44-82eb0d2defe9.png)

![Image](https://user-images.githubusercontent.com/278886/233865396-76e79db1-b296-473c-bca9-b93cc9e0a837.png)

![Image](https://user-images.githubusercontent.com/278886/232243008-14eeb170-f0f1-4bb3-8ad5-089fa33c0ba0.png)

![Image](https://user-images.githubusercontent.com/278886/232243083-b68415f4-1ed5-4f57-b77e-4d4ffe91f588.png)

![Image](https://user-images.githubusercontent.com/278886/232243451-7f46d793-ee62-4f59-ab0e-9ec3981ef119.png)

![Image](https://user-images.githubusercontent.com/278886/233865416-8b885618-3f33-4567-9306-dbd59f963dcf.png)

**Comment by carlaost** [comment]
If you have switched to the node stewards tab in my collection, everything is switched to primary color purple.

Node Stewards License decisions are "suggestions" and they get to choose "unknown" -- Original authors will need to make a final decision on all "unknowns" before confirming their authorship.
